name: pangeo
channels:
  - conda-forge
  - intake
  - default
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - ipywidgets
  - graphviz
  - jupyterlab=0.35
  - nodejs
  - pip:
    - kubernetes
    - graphviz
    - git+https://github.com/dask/dask-kubernetes.git
